name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Run flake8
      run: |
        flake8 .

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: pytest-report
        path: report.html

    - name: Upload flake8 report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: flake8-report
        path: flake8-report/index.html
